use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

/// Database model for the `admins` table.
///
/// Maps directly to `app/adminServer/migrations/001_create_admins.sql`.
/// See also `doc/protocol.md` §6.3.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct AdminModel {
    /// Primary key — UUID v4, generated by PostgreSQL `gen_random_uuid()`.
    pub id: Uuid,

    /// Unique login name (VARCHAR 50, UNIQUE constraint).
    pub username: String,

    /// bcrypt hash of the admin's password (VARCHAR 200).
    /// Must start with `$2b$` or `$2a$` and be ≥ 60 characters long.
    pub password_hash: String,

    /// RBAC role — one of: `super_admin`, `operator`, `cs`, `finance`.
    /// Enforced by a CHECK constraint in the database.
    pub role: String,

    /// Optional human-readable name shown in the admin UI (VARCHAR 100).
    pub display_name: Option<String>,

    /// When `false` the admin account is suspended and logins are rejected.
    pub is_active: bool,

    /// Timestamp of the most recent successful login; `None` for new accounts.
    pub last_login_at: Option<DateTime<Utc>>,

    /// Row creation timestamp (set by PostgreSQL `DEFAULT now()`).
    pub created_at: DateTime<Utc>,

    /// Row last-update timestamp (set by PostgreSQL `DEFAULT now()`).
    pub updated_at: DateTime<Utc>,
}
