use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

/// Database model for the `rooms` table.
///
/// Maps directly to `app/server/migrations/002_create_rooms.sql`
/// and `app/server/migrations/008_room_governance.sql`.
/// See also `doc/tds/server/T-00006.md` and `doc/tds/server/T-00024.md`.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct RoomModel {
    /// Primary key — UUID v4, generated by PostgreSQL `gen_random_uuid()`.
    pub id: Uuid,

    /// Foreign key to `users(id)` — the room owner.
    pub owner_id: Uuid,

    /// Room display title (1–30 characters, enforced by DB CHECK constraint).
    pub title: String,

    /// Room type — one of: `normal`, `password`, `paid`.
    /// Enforced by a CHECK constraint in the database.
    pub room_type: String,

    /// Current number of members in the room (≥ 0).
    pub member_count: i32,

    /// Room status — one of: `active`, `closed`.
    /// Enforced by a CHECK constraint in the database.
    pub status: String,

    /// bcrypt hash of the room password; `None` for non-password rooms.
    pub password_hash: Option<String>,

    /// Maximum allowed members (> 0, defaults to 50).
    pub max_members: i32,

    /// Row creation timestamp (set by PostgreSQL `DEFAULT NOW()`).
    pub created_at: DateTime<Utc>,

    /// Row last-update timestamp (set by PostgreSQL `DEFAULT NOW()`).
    pub updated_at: DateTime<Utc>,

    /// Soft-delete timestamp; `None` means the room has not been deleted.
    pub deleted_at: Option<DateTime<Utc>>,

    // ── T-00024: 治理字段 ─────────────────────────────────────────────────

    /// Room cover image URL. Empty string `""` means no cover (legacy rooms).
    /// Added by migration 008_room_governance.sql with DEFAULT ''.
    #[serde(default)]
    pub cover_url: String,

    /// Room category — one of: `chat`, `emotion`, `music`, `game`, `matchmaking`, `other`.
    /// Enforced by `chk_room_category` CHECK constraint.
    /// Added by migration 008_room_governance.sql with DEFAULT 'chat'.
    #[serde(default = "default_category")]
    pub category: String,

    /// Public announcement text for the room; `None` means no announcement.
    pub announcement: Option<String>,

    /// Optional designated admin user; `None` means no extra admin assigned.
    /// Foreign key to `users(id)`.
    pub admin_user_id: Option<Uuid>,
}

fn default_category() -> String {
    "chat".to_string()
}

#[cfg(test)]
mod tests {
    use chrono::Utc;
    use serde_json::Value;
    use uuid::Uuid;

    // ---- helper ----

    fn make_room() -> super::RoomModel {
        super::RoomModel {
            id: Uuid::new_v4(),
            owner_id: Uuid::new_v4(),
            title: "Test Room".to_string(),
            room_type: "normal".to_string(),
            member_count: 0,
            status: "active".to_string(),
            password_hash: None,
            max_members: 50,
            created_at: Utc::now(),
            updated_at: Utc::now(),
            deleted_at: None,
            // T-00024 governance fields
            cover_url: String::new(),
            category: "chat".to_string(),
            announcement: None,
            admin_user_id: None,
        }
    }

    // ---- Model trait tests ----

    #[test]
    fn test_room_model_clone() {
        let room = make_room();
        let cloned = room.clone();
        assert_eq!(room.id, cloned.id);
        assert_eq!(room.title, cloned.title);
        assert_eq!(room.owner_id, cloned.owner_id);
    }

    #[test]
    fn test_room_model_debug() {
        let room = make_room();
        let debug_str = format!("{:?}", room);
        assert!(debug_str.contains("RoomModel"));
        assert!(debug_str.contains("Test Room"));
    }

    #[test]
    fn test_room_model_serialize() {
        let room = make_room();
        let json = serde_json::to_string(&room).expect("serialize should succeed");
        let v: Value = serde_json::from_str(&json).unwrap();
        assert!(v["id"].is_string());
        assert!(v["owner_id"].is_string());
        assert_eq!(v["title"], "Test Room");
        assert_eq!(v["room_type"], "normal");
        assert_eq!(v["member_count"], 0);
        assert_eq!(v["status"], "active");
        assert_eq!(v["max_members"], 50);
        assert!(v["password_hash"].is_null());
        assert!(v["deleted_at"].is_null());
        // T-00024 governance fields
        assert_eq!(v["cover_url"], "");
        assert_eq!(v["category"], "chat");
        assert!(v["announcement"].is_null());
        assert!(v["admin_user_id"].is_null());
    }

    #[test]
    fn test_room_model_password_hash_nullable() {
        // None variant
        let mut room = make_room();
        assert!(room.password_hash.is_none());
        // Some variant
        room.password_hash = Some("$2b$12$hashed".to_string());
        assert_eq!(room.password_hash.as_deref(), Some("$2b$12$hashed"));
    }

    #[test]
    fn test_room_model_deleted_at_nullable() {
        let mut room = make_room();
        assert!(room.deleted_at.is_none());
        // soft-delete
        room.deleted_at = Some(Utc::now());
        assert!(room.deleted_at.is_some());
    }

    #[test]
    fn test_room_model_field_types() {
        let room = make_room();
        // member_count is i32 and defaults to 0
        assert_eq!(room.member_count, 0i32);
        // max_members is i32 and defaults to 50
        assert_eq!(room.max_members, 50i32);
        // room_type default
        assert_eq!(room.room_type, "normal");
        // status default
        assert_eq!(room.status, "active");
    }

    #[test]
    fn test_room_model_deserialize() {
        let json = r#"{
            "id": "00000000-0000-0000-0000-000000000001",
            "owner_id": "00000000-0000-0000-0000-000000000002",
            "title": "Cozy Room",
            "room_type": "password",
            "member_count": 5,
            "status": "active",
            "password_hash": "$2b$12$abc",
            "max_members": 20,
            "created_at": "2024-01-01T00:00:00Z",
            "updated_at": "2024-01-01T00:00:00Z",
            "deleted_at": null,
            "cover_url": "https://example.com/cover.jpg",
            "category": "music",
            "announcement": "Welcome to Cozy Room!",
            "admin_user_id": null
        }"#;
        let room: super::RoomModel = serde_json::from_str(json).expect("deserialize should succeed");
        assert_eq!(room.title, "Cozy Room");
        assert_eq!(room.room_type, "password");
        assert_eq!(room.member_count, 5);
        assert_eq!(room.password_hash.as_deref(), Some("$2b$12$abc"));
        // T-00024 governance fields
        assert_eq!(room.cover_url, "https://example.com/cover.jpg");
        assert_eq!(room.category, "music");
        assert_eq!(room.announcement.as_deref(), Some("Welcome to Cozy Room!"));
        assert!(room.admin_user_id.is_none());
    }

    #[test]
    fn test_room_model_deserialize_legacy_without_governance_fields() {
        // 旧 JSON 不含治理字段，应用 serde(default) 优雅降级
        let json = r#"{
            "id": "00000000-0000-0000-0000-000000000001",
            "owner_id": "00000000-0000-0000-0000-000000000002",
            "title": "Legacy Room",
            "room_type": "normal",
            "member_count": 0,
            "status": "active",
            "password_hash": null,
            "max_members": 50,
            "created_at": "2024-01-01T00:00:00Z",
            "updated_at": "2024-01-01T00:00:00Z",
            "deleted_at": null,
            "announcement": null,
            "admin_user_id": null
        }"#;
        let room: super::RoomModel = serde_json::from_str(json).expect("deserialize should succeed");
        // serde(default) 使 cover_url 默认为空串
        assert_eq!(room.cover_url, "");
        // serde(default = "default_category") 使 category 默认为 "chat"
        assert_eq!(room.category, "chat");
    }

    // ---- SQL migration file content tests ----

    fn load_migration() -> String {
        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../server/migrations/002_create_rooms.sql"
        );
        std::fs::read_to_string(path)
            .expect("002_create_rooms.sql must exist at app/server/migrations/")
    }

    #[test]
    fn test_migration_contains_rooms_table() {
        let sql = load_migration();
        assert!(
            sql.contains("CREATE TABLE IF NOT EXISTS rooms"),
            "SQL must contain rooms table creation"
        );
    }

    #[test]
    fn test_migration_contains_owner_id_fk() {
        let sql = load_migration();
        assert!(
            sql.contains("REFERENCES users(id)"),
            "SQL must contain foreign key to users(id)"
        );
    }

    #[test]
    fn test_migration_contains_title_check() {
        let sql = load_migration();
        assert!(
            sql.contains("chk_rooms_title_length"),
            "SQL must contain title length check constraint"
        );
        assert!(
            sql.contains("char_length(title)"),
            "SQL must check char_length of title"
        );
    }

    #[test]
    fn test_migration_contains_room_type_check() {
        let sql = load_migration();
        assert!(
            sql.contains("chk_rooms_room_type"),
            "SQL must contain room_type check constraint"
        );
        assert!(
            sql.contains("'normal'") && sql.contains("'password'") && sql.contains("'paid'"),
            "SQL must enumerate normal/password/paid room types"
        );
    }

    #[test]
    fn test_migration_contains_status_check() {
        let sql = load_migration();
        assert!(
            sql.contains("chk_rooms_status"),
            "SQL must contain status check constraint"
        );
        assert!(
            sql.contains("'active'") && sql.contains("'closed'"),
            "SQL must enumerate active/closed statuses"
        );
    }

    #[test]
    fn test_migration_contains_member_count_check() {
        let sql = load_migration();
        assert!(
            sql.contains("chk_rooms_member_count_non_negative"),
            "SQL must contain member_count non-negative check"
        );
    }

    #[test]
    fn test_migration_contains_max_members_check() {
        let sql = load_migration();
        assert!(
            sql.contains("chk_rooms_max_members_positive"),
            "SQL must contain max_members positive check"
        );
    }

    #[test]
    fn test_migration_contains_indexes() {
        let sql = load_migration();
        assert!(
            sql.contains("idx_rooms_status_created_at"),
            "SQL must contain composite index on status+created_at"
        );
        assert!(
            sql.contains("idx_rooms_owner_id"),
            "SQL must contain index on owner_id"
        );
        assert!(
            sql.contains("idx_rooms_member_count"),
            "SQL must contain index on member_count"
        );
    }

    #[test]
    fn test_migration_contains_soft_delete_column() {
        let sql = load_migration();
        assert!(
            sql.contains("deleted_at"),
            "SQL must include deleted_at for soft-delete support"
        );
    }

    #[test]
    fn test_migration_uses_uuid_primary_key() {
        let sql = load_migration();
        assert!(
            sql.contains("UUID") && sql.contains("gen_random_uuid()"),
            "SQL must use UUID PK with gen_random_uuid()"
        );
    }

    // ---- M-01: 外键 ON DELETE RESTRICT ----

    #[test]
    fn test_migration_owner_id_on_delete_restrict() {
        let sql = load_migration();
        assert!(
            sql.contains("REFERENCES users(id) ON DELETE RESTRICT"),
            "M-01: owner_id FK must have explicit ON DELETE RESTRICT"
        );
    }

    // ---- M-02: member_count <= max_members 上界约束 ----

    #[test]
    fn test_migration_member_count_le_max_check() {
        let sql = load_migration();
        assert!(
            sql.contains("chk_rooms_member_count_le_max"),
            "M-02: SQL must contain chk_rooms_member_count_le_max constraint"
        );
        assert!(
            sql.contains("member_count <= max_members"),
            "M-02: constraint must enforce member_count <= max_members"
        );
    }

    // ---- M-03: 热度/列表索引过滤软删除行 ----

    #[test]
    fn test_migration_status_index_filters_soft_deleted() {
        let sql = load_migration();
        assert!(
            sql.contains("idx_rooms_status_created_at") && sql.contains("WHERE deleted_at IS NULL"),
            "M-03: idx_rooms_status_created_at must have WHERE deleted_at IS NULL partial filter"
        );
    }

    #[test]
    fn test_migration_member_count_index_filters_soft_deleted() {
        let sql = load_migration();
        // The member_count index line must itself carry the WHERE clause.
        let has_partial_member_count_idx = sql
            .lines()
            .any(|l| l.contains("idx_rooms_member_count") && l.contains("WHERE deleted_at IS NULL"));
        assert!(
            has_partial_member_count_idx,
            "M-03: idx_rooms_member_count must have WHERE deleted_at IS NULL partial filter"
        );
    }
}

