#!/usr/bin/env bash
# T-0000G: E2E Seed wrapper（幂等）
#
# 仅在 E2E_PROFILE=local 且 E2E_ALLOW_WRITES=1 时允许执行。
# 流程：
#   1) 双 env 校验 + JWT 密钥校验（fail-fast，不 echo 密钥）
#   2) 调 scripts/dev 内的 sign-jwt CLI 算 7 个 UUIDv5 + 签 5 个 token
#   3) psql -v 注入 ID 入参，跑 seed-e2e.sql（幂等 ON CONFLICT）
#   4) 把 8 项回填字段写到 scripts/dev/.seed-output.env（gitignored）
#
# 退出码（与 TDS §2.7 globalSetup 契约一致）：
#   0 成功 / 21 profile 拒绝 / 22 JWT 签发失败（含缺少 secret） / 23 SQL 执行失败
#
# 安全：set +x；JWT_SECRET / *_JWT_SECRET 永不进入日志或 .seed-output.env。

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT_FILE="${REPO_ROOT}/scripts/dev/.seed-output.env"
SEED_SQL="${REPO_ROOT}/scripts/dev/seed-e2e.sql"
LOCK_FILE="${REPO_ROOT}/scripts/dev/.seed.lock"

# -------- 1. profile 校验 --------
profile="${E2E_PROFILE:-}"
if [[ "${profile}" != "local" ]]; then
    echo "[seed] refuse: E2E_PROFILE=${profile:-<unset>}, only 'local' is allowed" >&2
    exit 21
fi
if [[ "${E2E_ALLOW_WRITES:-0}" != "1" ]]; then
    echo "[seed] refuse: E2E_ALLOW_WRITES must be 1" >&2
    exit 21
fi

# -------- 2. JWT 密钥校验（不 echo） --------
APP_SECRET="${APP_JWT_SECRET:-${JWT_SECRET:-}}"
ADMIN_SECRET="${ADMIN_JWT_SECRET:-${JWT_SECRET:-}}"
if [[ -z "${APP_SECRET}" || -z "${ADMIN_SECRET}" ]]; then
    echo "[seed] JWT_SECRET is required (set APP_JWT_SECRET + ADMIN_JWT_SECRET, or JWT_SECRET as fallback)" >&2
    exit 22
fi

TTL="${E2E_TOKEN_TTL_SECONDS:-86400}"

# -------- 3. 定位 sign-jwt CLI --------
SIGN_JWT="${SIGN_JWT_BIN:-}"
if [[ -z "${SIGN_JWT}" ]]; then
    if [[ -x "${REPO_ROOT}/target/debug/sign-jwt" ]]; then
        SIGN_JWT="${REPO_ROOT}/target/debug/sign-jwt"
    elif [[ -x "${REPO_ROOT}/target/release/sign-jwt" ]]; then
        SIGN_JWT="${REPO_ROOT}/target/release/sign-jwt"
    else
        echo "[seed] step=1 building sign-jwt CLI ..." >&2
        if ! ( cd "${REPO_ROOT}" && cargo build -q -p voice-room-shared --bin sign-jwt ); then
            echo "[seed] sign-jwt build failed" >&2
            exit 22
        fi
        SIGN_JWT="${REPO_ROOT}/target/debug/sign-jwt"
    fi
fi

# -------- 4. flock 串行（CI 多 job 兜底，G-R4） --------
exec 9>"${LOCK_FILE}"
if command -v flock >/dev/null 2>&1; then
    flock -w 30 9 || { echo "[seed] could not acquire lock ${LOCK_FILE}" >&2; exit 23; }
fi

set +x

uuid5() {
    "${SIGN_JWT}" --uuid5 "$1"
}

sign() {
    # $1=secret_value $2=sub $3=role $4=ttl
    JWT_SECRET="$1" "${SIGN_JWT}" --sub "$2" --role "$3" --ttl "$4"
}

echo "[seed] step=2 computing deterministic UUIDv5 ids"
USER_A_ID=$(uuid5 user_a)
USER_B_ID=$(uuid5 user_b)
USER_MUTED_ID=$(uuid5 user_muted)
ROOM_ID=$(uuid5 room_main)
ADMIN_SUPER_ID=$(uuid5 admin_super)
ADMIN_OP_ID=$(uuid5 admin_op)
ADMIN_CS_ID=$(uuid5 admin_cs)
ADMIN_FIN_ID=$(uuid5 admin_fin)
ADMIN_DISABLED_ID=$(uuid5 admin_disabled)

echo "[seed] step=3 signing JWT tokens (ttl=${TTL}s)"
VALID_TOKEN=$(sign "${APP_SECRET}"   "${USER_A_ID}"     user  "${TTL}")
USER_B_TOKEN=$(sign "${APP_SECRET}"  "${USER_B_ID}"     user  "${TTL}")
MUTED_TOKEN=$(sign "${APP_SECRET}"   "${USER_MUTED_ID}" user  "${TTL}")
ADMIN_TOKEN=$(sign "${ADMIN_SECRET}" "${ADMIN_SUPER_ID}" admin "${TTL}")
OP_TOKEN=$(sign    "${ADMIN_SECRET}" "${ADMIN_OP_ID}"    op    "${TTL}")
CS_TOKEN=$(sign    "${ADMIN_SECRET}" "${ADMIN_CS_ID}"    cs    "${TTL}")
FIN_TOKEN=$(sign   "${ADMIN_SECRET}" "${ADMIN_FIN_ID}"   fin   "${TTL}")

# -------- 5. psql 跑 SQL --------
echo "[seed] step=4 applying seed SQL"
PSQL_ARGS=(
    -v "ON_ERROR_STOP=1"
    -v "user_a_id=${USER_A_ID}"
    -v "user_b_id=${USER_B_ID}"
    -v "user_muted_id=${USER_MUTED_ID}"
    -v "room_id=${ROOM_ID}"
    -v "admin_super_id=${ADMIN_SUPER_ID}"
    -v "admin_op_id=${ADMIN_OP_ID}"
    -v "admin_cs_id=${ADMIN_CS_ID}"
    -v "admin_fin_id=${ADMIN_FIN_ID}"
    -v "admin_disabled_id=${ADMIN_DISABLED_ID}"
)

if ! command -v psql >/dev/null 2>&1; then
    echo "[seed] psql not found in PATH" >&2
    exit 23
fi

# 优先使用 SEED_DATABASE_URL（超级用户权限），否则尝试 postgres 超级用户
SEED_DB_URL="${SEED_DATABASE_URL:-postgres://postgres:postgres@localhost:5432/voiceroom}"

if ! psql "${SEED_DB_URL}" "${PSQL_ARGS[@]}" < "${SEED_SQL}" >/dev/null; then
    echo "[seed] SQL execution failed" >&2
    exit 23
fi

# -------- 6. 写回填文件（不含密钥/不含已过期 token） --------
umask 077
TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
cat > "${OUT_FILE}" <<EOF
# Generated by scripts/dev/seed-e2e.sh at ${TS}
# DO NOT COMMIT. .gitignore covers this file.
E2E_USER_A_ID=${USER_A_ID}
E2E_USER_B_ID=${USER_B_ID}
E2E_USER_MUTED_ID=${USER_MUTED_ID}
E2E_ROOM_ID=${ROOM_ID}
E2E_VALID_TOKEN=${VALID_TOKEN}
E2E_USER_B_TOKEN=${USER_B_TOKEN}
E2E_MUTED_TOKEN=${MUTED_TOKEN}
E2E_ADMIN_TOKEN=${ADMIN_TOKEN}
E2E_OP_TOKEN=${OP_TOKEN}
E2E_CS_TOKEN=${CS_TOKEN}
E2E_FIN_TOKEN=${FIN_TOKEN}
EOF

echo "seed: wrote scripts/dev/.seed-output.env"

# -------- 7. T-0000S: 写入禁言态到 Redis（chat_muted:{room}:{user_muted}） --------
# 真值：app/server/src/modules/governance/mute.rs 读取 key `chat_muted:{room_id}:{user_id}`，
# 命中即在 SendMessage 前置返回 40303。TTL 86400s 与 token 一致（24h）。
# 容器名：vr-redis（docker-compose.yml `container_name: vr-redis`）。
# 失败仅 warn，不阻塞 seed 整体退出码（globalSetup 会再做一次自检诊断）。
if command -v docker >/dev/null 2>&1 && docker ps --format '{{.Names}}' 2>/dev/null | grep -q '^vr-redis$'; then
    if docker exec vr-redis redis-cli SETEX "chat_muted:${ROOM_ID}:${USER_MUTED_ID}" 86400 1 >/dev/null 2>&1; then
        echo "[seed] step=5 chat_muted Redis key set via docker exec vr-redis"
    else
        echo "[seed] step=5 WARN: failed to SETEX chat_muted via docker exec vr-redis (TC-CHAT-00004 may skip)" >&2
    fi
elif command -v redis-cli >/dev/null 2>&1; then
    if redis-cli SETEX "chat_muted:${ROOM_ID}:${USER_MUTED_ID}" 86400 1 >/dev/null 2>&1; then
        echo "[seed] step=5 chat_muted Redis key set via local redis-cli"
    else
        echo "[seed] step=5 WARN: failed to SETEX chat_muted via local redis-cli" >&2
    fi
else
    echo "[seed] step=5 WARN: no docker(vr-redis) nor redis-cli; skipping mute state injection" >&2
fi
exit 0
